# usage: docker build -f dockerfile.onnx.prod -t ruhyadi/vision-fr:v1.0.0 .

FROM python:3.10-slim

# install debian dependencies
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && apt-get install -y --no-install-recommends \
    curl wget ffmpeg libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# install python dependencies
COPY ./requirements.onnx.prod.txt /tmp/requirements.txt
ENV PIP_DEFAULT_TIMEOUT=600
RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir -r /tmp/requirements.txt
RUN rm /tmp/requirements.txt

# copy source code
COPY . /app
RUN mkdir -p /app/logs /app/tmp

# default workdir
WORKDIR /app

# entrypoint
# CMD ["python /app/src/main.py"]
CMD ["bash"]